spring.profiles.default=local

spring.jpa.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

server.servlet.context-path=/gym-crm

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator