spring.application.name=gym-workload
server.port=8081

spring.datasource.url=jdbc:h2:mem:workloaddb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT Security Secret
jwt.secret=9a74132a4e214c7784f18b32c69d8d1e2f3g4h5j6k7l8m9n0p1q2r3s4t5u6v7w

# --- ActiveMQ Configuration ---
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# --- Queue Names ---
app.queue.trainer-workload=trainer-workload-queue